version: '3.4'

services:

  sead.query.api:
    image: sead_query_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis.cache
    networks:
      sead_query_net:
        ipv4_address: 172.21.128.1

  redis.cache:
    image: "${REDIS_DOCKER_TAG:-redis:5-alpine}"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    volumes:
      - ${REDIS_DATA_DIR:-/tmp}:/data
    networks:
      sead_query_net:
        ipv4_address: 172.21.128.2

networks:
  sead_query_net:
    ipam:
      config:
        - subnet: 172.21.0.0/16
