version: '3.4'

services:
  sead.query.api:
    image: ${DOCKER_REGISTRY-}sead_query_api
    build:
      context: .
      dockerfile: sead_query_api/Dockerfile
    depends_on:
      - data.cache
  data.cache:
    image: redis
