version: '3.4'

services:

  sead.query.api:
    image: sead_query_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis.cache
    networks:
      - sead_query_net

  redis.cache:
    image: "${REDIS_DOCKER_TAG:-redis:5-alpine}"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    volumes:
      - ${REDIS_DATA_DIR:-/tmp}:/data
    networks:
      - sead_query_net

networks:
  sead_query_net:
