version: '3.4'

services:
  sead.query.api:
    image: ${DOCKER_REGISTRY-}sead_query_api
    build:
      context: .
      dockerfile: sead_query_api/Dockerfile
    depends_on:
      - data.cache
  data.cache:
    container_name: REDIS
    hostname: ${REDIS_HOSTNAME}
    image: redis:4.0.10
    expose:
      - ${REDIS_CONTAINER_PORT}
    volumes:
      - redisdata:/data
    networks:
      - sead_query
